trigger: none

pr:
  branches:
    include:
      - main

pool:
  vmImage: ubuntu-latest

steps:
- bash: |
    echo "Hello, world!"
  displayName: Run a one-line Bash script

- bash: |
    echo "Add other tasks to build, test, and deploy your project."
    echo "See https://aka.ms/yaml"
  displayName: Run a multi-line Bash script

- bash: |
    echo "Sleeping for 10 minutes..."
    sleep 600
    echo "Sleep completed."
  displayName: Long-running Bash script